language: java
install: mvn install -DskipTests=true
jdk:
  - oraclejdk8
before_install:
  - pip install --user codecov

# Codacy - https://github.com/codacy/codacy-coverage-reporter#setup
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
#  - codecov
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
