environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0

skip_tags: true  
shallow_clone: true

install:
  - ps: choco install maven
  - cmd: SET PATH=C:\tools\apache-maven-3.3.3\bin;%JAVA_HOME%\bin;%PATH%
  - mvn --version

build_script:
  - mvn clean package -DskipTests
test_script:
  - mvn test
 
deploy: off
cache:
  - C:\Users\appveyor\.m2
