version: '{build}'
skip_tags: true
shallow_clone: true

environment:
  matrix:
    #- JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0
    #- JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
branches:
  only:
    - master

os: Visual Studio 2015
#image: Visual Studio 2015
#platform:
#  - Win32

install:
  - cinst PhantomJS -y -Version 2.1.1
  - set path=%path%;C:\tools\PhantomJS\;C:\ProgramData\chocolatey\lib\PhantomJS\tools;C:\ProgramData\chocolatey\lib\PhantomJS

  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\tools")
      }
  - cmd: SET PATH=C:\tools\apache-maven-3.3.9\bin;%JAVA_HOME%\bin;%PATH%

build_script:
  - mvn clean package -DskipTests -Dmaven.javadoc.skip=true -Djna.nosys=true
test_script:
  - mvn test -Dmaven.javadoc.skip=true -Djna.nosys=true

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh

cache:
#  - C:\tools\PhantomJS\
#  - C:\tools\apache-maven-3.3.9\
  - C:\Users\appveyor\.m2
