version: '{build}'
skip_tags: true
shallow_clone: true

environment:
  matrix:
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0
    #- JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    #- JAVA_HOME: C:\Program Files\Java\jdk1.8.0
branches:
  only:
    - master

os: Visual Studio 2015

install:
  - cinst PhantomJS -y -Version 1.9.8
  - set path=%path%;C:\tools\PhantomJS\
  - ps: choco install maven
  - cmd: SET PATH=C:\tools\apache-maven-3.3.3\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: mvn --version
  - cmd: java -version

build_script:
  - mvn clean package -DskipTests
test_script:
  - mvn clean test

cache:
  - C:\tools\PhantomJS\
  - C:\tools\apache-maven-3.3.3\
  - C:\Users\appveyor\.m2
