version: '{build}'
skip_tags: true
shallow_clone: true

environment:
  matrix:
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0
    #- JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    #- JAVA_HOME: C:\Program Files\Java\jdk1.8.0
branches:
  only:
    - master

os: Visual Studio 2015

install:
  - cinst PhantomJS -y -Version 2.1.1
  - set path=%path%;C:\tools\PhantomJS\
  - ps: choco install maven 3.3.9
  - cmd: SET PATH=C:\tools\apache-maven-3.3.9\bin;%JAVA_HOME%\bin;%PATH%

build_script:
  - mvn clean package -DskipTests
test_script:
  - mvn clean test

cache:
  - C:\tools\PhantomJS\
  - C:\tools\apache-maven-3.3.9\
  - C:\Users\appveyor\.m2
